/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event emitted after DynamoDB persistence.
 */
export interface EtlPersistedV1 {
  schema: "etl.persisted.v1";
  metadata: {
    tenantId: string;
    persistedAt: string;
    traceId: string;
  };
  record: {
    pk: string;
    sk: string;
    gsi1pk: string;
    gsi1sk: string;
    entityType: string;
    version?: string;
    entityId: string;
    attributes?: {
      [k: string]: unknown;
    };
  };
}
