/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Normalized record produced by Normalize service.
 */
export interface EtlNormalizedV1 {
  schema: "etl.normalized.v1";
  metadata: {
    tenantId: string;
    source: string;
    normalizedAt: string;
    idempotencyKey: string;
    /**
     * Propagation id for observability.
     */
    traceId: string;
  };
  data: {
    entityType: "study" | "series" | "instance" | "patient" | "encounter" | "generic" | "observation";
    entityId: string;
    patientId?: string;
    encounterId?: string;
    modality?: string;
    /**
     * Flattened, mapped keys after normalization.
     */
    attributes?: {
      [k: string]: unknown;
    };
  };
}
