/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Raw payload envelope as accepted by Ingest API.
 */
export interface IngestRawV1 {
  schema: "ingest.raw.v1";
  metadata: {
    tenantId: string;
    /**
     * Origin system identifier (e.g., 'orthanc', 'dcm4chee', 'ehr-x').
     */
    source: string;
    ingestedAt: string;
    /**
     * Client-provided dedupe key (hash of payload recommended).
     */
    idempotencyKey: string;
    /**
     * SHA-256 of payload bytes (optional but recommended).
     */
    contentHash?: string;
  };
  /**
   * Opaque raw data from source system.
   */
  payload: {
    [k: string]: unknown;
  };
}
